# .github/workflows/run_python_script.yml

name: Run Python Script

on:
  schedule:
    - cron: '*/5 3-9 * * 1-5'  # Runs every 5 minutes between 3:44 AM and 9:59 AM UTC, Monday to Friday
  workflow_dispatch:  # Allows you to manually trigger the workflow if needed

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with the desired Python version, e.g., 3.8

      - name: Install dependencies
        run: |
          # If you have dependencies, install them here
          # For example:
          # pip install -r requirements.txt
          echo "No dependencies to install"

      - name: Run script
        run: |
          python script.py
